In [2]:
import pandas as pd
from utils.preprocess import load_data

In [6]:
df = load_data('./data/train_FD001.txt')
df.describe()

          engine_id         cycle  ...     sensor_18     sensor_19
count  20631.000000  20631.000000  ...  20631.000000  20631.000000
mean      -0.000009      0.000002  ...     38.816271     23.289705
std        0.002187      0.000293  ...      0.180746      0.108251
min       -0.008700     -0.000600  ...     38.140000     22.894200
25%       -0.001500     -0.000200  ...     38.700000     23.221800
50%        0.000000      0.000000  ...     38.830000     23.297900
75%        0.001500      0.000300  ...     38.950000     23.366800
max        0.008700      0.000600  ...     39.430000     23.618400

[8 rows x 24 columns]